codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        informational: false       # Make patch coverage blocking to show in comments
        target: 80%
        threshold: 50%             # Allow some flexibility

ignore:
  - "**/*__data__*/*.ts"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: new              # Update existing comments instead of creating new ones
  require_changes: false
  require_base: true         # Require base coverage for proper comparison
  require_head: true         # Require head coverage to post comment
  after_n_builds: 1          # Only wait for one build since unit tests might not run on every PR
  
