name: 'PR Check Test'
description: 'Reusable action for running konflux-ui E2E test against konflux-ci instance deployed on kind cluster'
inputs:
  job-type:
    description: '"on-pr" or "periodic"'
    required: true

runs:
  using: "composite"  
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        docker-images: false

    # konflux-ci is cloned to /home/runner/work/konflux-ui/konflux-ui
    # as it have to be at home folder to use helm/kind-action@v1 action
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: 'konflux-ci/konflux-ci'
        ref: 'main'

    - name: Disable AppArmor
      # works around a change in ubuntu 24.04 that restricts Linux namespace access
      # for unprivileged users
      run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      shell: bash

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
      with:
        config: kind-config.yaml
        cluster_name: konflux
    
    - name: Show version information
      run: |
        kubectl version
        kind version
      shell: bash

    - name: List namespaces
      run: |
        kubectl get namespace
      shell: bash

    - name: Deploying Dependencies
      run: |
        ./deploy-deps.sh
      shell: bash

    - name: List namespaces
      run: |
        kubectl get namespace
      shell: bash

    - name: Wait for the dependencies to be ready
      run: |
        ./wait-for-all.sh
      shell: bash

    - name: WORKAROUND - Reduce CPU/Memory requirements in build pipeline
      run: |
        sed -i "s|pipelinesascode.tekton.dev/original-prname:.*|pipelinesascode.tekton.dev/original-prname: \"java-quarkus-*\"|g" ./dependencies/kyverno/policy/e2e-reduce-resources.yaml
        kubectl create -f  ./dependencies/kyverno/policy/e2e-reduce-resources.yaml
      shell: bash

    # konflux-ui repo is cloned to /home/runner/work/konflux-ui/konflux-ui/konflux-ui
    - name: Checkout Konflux-UI Repository
      uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
        path: 'konflux-ui'

    - name: Build konflux-ui image
      env:
        CYPRESS_GH_TOKEN: ${{ secrets.HAC_TEST_GH_TOKEN }}
        TARGET_BRANCH: ${{ github.base_ref }}
        SOURCE_BRANCH: ${{ github.head_ref }}
        PR_NUMBER: ${{ github.event.number }}
        HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
        SEALIGHTS_TOKEN: "${{ secrets.SEALIGHTS_TOKEN }}"
        FORKED_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}
        BASE_REPO_URL: ${{ github.event.pull_request.base.repo.clone_url }}
        JOB_TYPE: ${{ inputs.job-type }}
      run: |
        ./konflux-ui/pr_check.sh build
      shell: bash

    - name: Deploying Konflux
      run: |
        ./deploy-konflux.sh
      shell: bash

    - name: List namespaces
      run: |
        kubectl get namespace
      shell: bash

    - name: Deploy test resources
      run: |
        ./deploy-test-resources.sh
      shell: bash

    - name: Prepare resources for E2E tests
      # Sets secrets, deploys image controller and setup smee.
      env:
        APP_ID: ${{ secrets.GH_APP_ID }}
        APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
        APP_WEBHOOK_SECRET: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
        QUAY_ORG: ${{ secrets.QUAY_TEST_ORG }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN_TEST }}
        SMEE_CHANNEL: ${{ secrets.SMEE_URL }}
      run: |
        ./test/e2e/prepare-e2e.sh
      shell: bash

    - name: Install Konflux-UI and run tests
      env:
        CYPRESS_GH_TOKEN: ${{ secrets.HAC_TEST_GH_TOKEN }}
        TARGET_BRANCH: ${{ github.base_ref }}
        PR_NUMBER: ${{ github.event.number }}
        HEAD_SHA: "${{ github.event.pull_request.head.sha }}"
        CYPRESS_USERNAME: "${{ secrets.CYPRESS_USERNAME }}"
        CYPRESS_PASSWORD: "${{ secrets.CYPRESS_PASSWORD }}"
        SEALIGHTS_TOKEN: "${{ secrets.SEALIGHTS_TOKEN }}"
      run: | 
        ./konflux-ui/pr_check.sh test
      shell: bash
    
    - name: Generate error logs
      if: ${{ !cancelled() }}
      run: |
        ./generate-err-logs.sh
        cp -r konflux-ui/artifacts logs
      shell: bash

    - name: Archive logs
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs
