name: Build and Push Base Test Image

# trigger manually
on: workflow_dispatch

jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Build and Push Base Image
        env:
          QUAY_ORG: ${{ secrets.QUAY_TEST_ORG }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN_TEST }}
        run: |
          podman login -u="$QUAY_ORG" -p="$QUAY_TOKEN" quay.io
          podman build -t "quay.io/psturc/konflux-ui:${{ github.sha }}" -f Dockerfile.e2e-coverage
          podman push "quay.io/psturc/konflux-ui:${{ github.sha }}"
