name: Periodic job - test Konflux UI with Sealights

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy konflux-ci, build konflux-ui image and test
        id: pr-check-action
        uses: ./.github/actions/konflux-ui-deploy-test
        env:
          TARGET_BRANCH: ${{ github.base_ref }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          HEAD_SHA: ${{ github.sha }}
        with:
          job-type: 'periodic'
          hac-test-gh-token: ${{ secrets.HAC_TEST_GH_TOKEN }}
          sealights-token: ${{ secrets.SEALIGHTS_TOKEN }}
          gh-app-id: ${{ secrets.GH_APP_ID }}
          gh-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          gh-app-webhook-secret: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
          quay-test-org: ${{ secrets.QUAY_TEST_ORG }}
          quay-token-test: ${{ secrets.QUAY_TOKEN_TEST }}
          smee-url: ${{ secrets.SMEE_URL }}
          cypress-username: ${{ secrets.CYPRESS_USERNAME }}
          cypress-password: ${{ secrets.CYPRESS_PASSWORD }}