name: PR Check Test

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:

  deploy-konfux-ui:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.base_ref }}
      SOURCE_BRANCH: ${{ github.head_ref }}
      PR_NUMBER: ${{ github.event.number }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      FORKED_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}
      BASE_REPO_URL: ${{ github.event.pull_request.base.repo.clone_url }}
      # secrets
      CYPRESS_GH_TOKEN: ${{ secrets.HAC_TEST_GH_TOKEN }}
      HAC_TEST_GH_TOKEN: ${{ secrets.HAC_TEST_GH_TOKEN }}
      SEALIGHTS_TOKEN: ${{ secrets.SEALIGHTS_TOKEN }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      GH_APP_WEBHOOK_SECRET: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
      QUAY_TEST_ORG: ${{ secrets.QUAY_TEST_ORG }}
      QUAY_TOKEN_TEST: ${{ secrets.QUAY_TOKEN_TEST }}
      SMEE_URL: ${{ secrets.SMEE_URL }}
      CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
      CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
      TESTING_CLUSTER_API_URL: ${{ secrets.TESTING_CLUSTER_API_URL }}
      KONFLUX_UI_URL: ${{ secrets.KONFLUX_UI_URL }}
      TESTING_CLUSTER_PASSWORD: ${{ secrets.TESTING_CLUSTER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: "${{ github.event.pull_request.head.sha }}"
  
      - name: Konflux-ui e2e test
        uses: ./.github/actions/konflux-ui-e2e-test
  
      - name: Generate error logs
        if: ${{ always() }}
        uses: ./.github/actions/generate-error-logs
